### ISSUE TITLE
issues with building

### ISSUE THREAD

**Issue by Jarled** [ltguillaume/thorium-winupdater#3]
1. Would prefer a built exe instead please.
2. When downloading the repo and following build BUILDING.MD instructions, found the `build.bat` was not included
3. I didn't know how to use Ahk2Exe, so went down the Resource Hacker route. so some simple instructions would help.
4. Running the .bat file it gave the following error 
![image](https://github.com/ltguillaume/thorium-winupdater/assets/45340322/0375c4a8-e0cb-4613-9f57-e439d24bb5f0)

5. I removed the line of code and run the bat again and the error said to use Ahk2Exe to specify the base file so i guessed it was `v1.1.37.01 U32 Ahk2Exe.exe` out of all the options 
![image](https://github.com/ltguillaume/thorium-winupdater/assets/45340322/740fb1cd-4779-4f3a-a39c-296896803743)
based on that it had to downloaded earlier to run the script.

Then it finally built so some more documentation, tutorial or video tutorial would have saved me time thanks.

**Comment by ltguillaume** [comment]
I'm not sure where you got AutoHotkey from, but the names of your `.bin` files seem customized. Normally, there are only 3 files, and one of them is `Unicode 32-bit.bin`.

As seen on https://github.com/ltguillaume/thorium-winupdater/releases, binaries are already available:
>You can find the latest release at https://codeberg.org/ltguillaume/thorium-winupdater/releases/latest
>
>WinUpdater also automatically updates itself if necessary.
