### ISSUE TITLE
How does one get rid of thorium Win-Updater

### ISSUE THREAD

**Issue by jeebuscrossaint** [ltguillaume/thorium-winupdater#6]
Hey I love thorium and all but I uninstalled thorium and reinstalled using scoop instead portable mode and wanted to know how to get rid of the thorium win updater powershell checker.

**Comment by ltguillaume** [comment]
Ah, Scoop is great!

If you've already gotten rid of WinUpdater, you can just open the Task Scheduler from the Start menu and remove the task `Thorium WinUpdater ([username])`.

**Comment by jeebuscrossaint** [comment]
Quite a quick response, good job man I actually just checked the repo again and you have a scheduled task remover script as well so I used that lol, thanks!

**Comment by ltguillaume** [comment]
Yeah, as you can see on the screenshot, normally you can just uncheck the option in WinUpdater itself (which simply runs that remover script), but I figured you might have removed Thorium/WinUpdater already then.

I've been dabbling with my own Scoop bucket, too: https://github.com/ltguillaume/schep Scoop's a bit rough around the edges, but it works great.
